on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-linux:
    if: github.repository_owner == 'oneapi-src'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3.6.0
      - uses: hendrikmuhs/ccache-action@ca3acd2731eef11f1572ccb126356c2cee1a3aa9 #v1.2.14
      - name: Build Loader on Latest Ubuntu
        run: |
          mkdir build
          cd build
          cmake \
            -D CMAKE_C_COMPILER_LAUNCHER=ccache \
            -D CMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -D CMAKE_BUILD_TYPE=Release \
            ..
          make -j$(nproc)
  build-windows:
    if: github.repository_owner == 'oneapi-src'
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3.6.0
      - name: Build Loader on Latest Windows
        shell: pwsh
        run: |
          mkdir build
          cd build
          cmake -D CMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release